import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  platformSidebar: [
    { type: "doc", id: "platform/appse-ai", label: "What is appse ai?" },
    /*{
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
        title: "Getting Started",
        description:
          "Familiarize yourself with the appse ai platform by building your very first flow.",
        slug: "/platform/getting-started/",
      },
      items: [
        {
          type: "category",
          label: "Create Your First Flow",
          items: [
            {
              type: "autogenerated",
              dirName: "platform/getting_started/create-flow",
            },
          ],
        },
        {
          type: "category",
          label: "Create Your First AI Agent",
          items: [
            // "platform/get_started/create-ai-agent/intro",
            {
              type: "autogenerated",
              dirName: "platform/getting_started/create-ai-agent",
            },
          ],
        },
      ],
    },*/
    {
      type: "category",
      label: "Key Concepts",
      link: {
        type: "generated-index",
        title: "Key Concepts",
        description:
          "Learn about the key concepts used in the platform to create dynamic and flexible workflows.",
        slug: "/platform/key-concepts/",
      },
      collapsed: false, // <--- ensure default expanded
      items: [
        //"platform/key_concepts/introduction",
        { type: "autogenerated", dirName: "platform/key_concepts" },
      ],
    },
    {
      type: "category",
      label: "Additional Options",
      link: {
        type: "generated-index",
        title: "Additional Options",
        description:
          "Learn about the additional features present on the platform.",
        slug: "/platform/additional-options/",
      },
      items: [
        //"platform/additional_options/introduction",
        { type: "autogenerated", dirName: "platform/additional_options" },
      ],
    },
    {
      type: "category",
      label: "Billing",
      link: {
        type: "generated-index",
        title: "Billing",
        description:
          "Understand how credits work and manage your billing on the appse ai platform.",
        slug: "/platform/billing/",
      },
      items: [
        { type: "autogenerated", dirName: "platform/billing" },
      ],
    },
    {
      type: "category",
      label: "Release Notes",
      link: {
        type: "generated-index",
        title: "Release Notes",
        description:
          "Check out the latest updates and improvements in our platform.",
        slug: "/platform/release-notes/",
      },
      items: [
        { type: "autogenerated", dirName: "platform/release_notes" },
      ],
    },
    {},
    // { type: "autogenerated", dirName: "platform" },
  ],
  app_integrationSidebar: [
    { type: "autogenerated", dirName: "app_integrations" },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;